server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: admin
  datasource:
    url: jdbc:h2:file:./config/database/mybase
    driverClassName: org.h2.Driver
    username: sa
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: for-you@kingofgarant.ru
    password: 33DA078A0EC9C847707267F58A8530E17BAB
    properties:
      mail:
        smtp:
          timeout: 100000
          connectiontimeout: 100000
          auth: true
          starttls.enable: true
logging:
  #file: /var/log/mail-sender
  level:
    org.springframework: info
    org.apache.http: info
    is.toxic: info
    org.springframework.integration.handler.LoggingHandler: off
  file:
    name: /opt/GMD/logs/GMD.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
GMD:
  max-in-cache: 2000
  storage-time: 2
  storage-unit: Days
  min-guarantee: 50000
  max-guarantee: 50000000
  max-in-day: 99
  max-in-pack: 10
  gosbase-url: https://gosbase.ru/v1/api/online/
  apikey: d428e943654ed9c66a1b22ca8fece014
  mail-subject: Для FIRM_NAME, предложение по предоставлению банковских гарантий
