spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
logging:
  #file: /var/log/mail-sender
  level:
    org.springframework: info
    org.apache.http: info
    is.toxic: info
    org.springframework.integration.handler.LoggingHandler: off
  file:
    name: /opt/GMD/logs
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
GMD:
  gosbase-url: https://gosbase.ru/v1/api/online/
  distribution-on: true
  apikey: d428e943654ed9c66a1b22ca8fece014
  mail-subject: для FIRM_NAME - Предложение по предоставлению банковских гарантий (от 1,5% годовых) как на участие, так и на исполнение и на кредитование (от 13% годовых) в рамках 44, 223 и 185-ФЗ (615-ПП) с максимальной величиной лимита до 3 миллиардов рублей
